export const GUEST_WELCOME_LANGUAGES = [["bs", "Bosanski"], ["en", "English"], ["de", "Deutsch"], ["tr", "Türkçe"], ["ar", "العربية"]];

const commonWeather = {
  0: "sunny", 1: "mostlySunny", 2: "partlyCloudy", 3: "cloudy", 45: "foggy", 48: "foggy",
  51: "drizzle", 53: "drizzle", 55: "drizzle", 56: "drizzle", 57: "drizzle",
  61: "rain", 63: "rain", 65: "rain", 66: "rain", 67: "rain", 71: "snow", 73: "snow", 75: "snow", 77: "snow", 80: "rain", 81: "rain", 82: "rain", 85: "snow", 86: "snow", 95: "storm", 96: "storm", 99: "storm",
};

function withWeather(copy) {
  const labels = copy.weatherLabels;
  return { ...copy, weatherConditions: Object.fromEntries(Object.entries(commonWeather).map(([code, key]) => [code, labels[key]])) };
}

export const GUEST_WELCOME_COPY = {
  bs: withWeather({
    language: "Jezik", welcome: "Dobro došli", room: "Soba", quickInfo: "Osnovne informacije", wifi: "Wi‑Fi", copyPassword: "Kopiraj lozinku", passwordCopied: "Lozinka kopirana", copyError: "Lozinku nije moguće kopirati", weather: "Vrijeme", weatherLoading: "Učitavanje vremena", weatherUnavailable: "Vrijeme nije dostupno", breakfast: "Doručak", wellness: "Wellness", restaurantRoomService: "Restoran i room service", menuOrder: "Meni i naručivanje", menuText: "Hrana, piće i room service", viewMenu: "Pogledaj meni", hotelServices: "Hotelske usluge", wellnessText: "Usluge i sadržaji", hotelInformation: "Hotelske informacije", hotelInformationText: "Pravila i informacije", call: "Pozovi osoblje", callText: "Zatražite pomoć u sobi", location: "Lokacija", locationText: "Mapa i put", poweredBy: "Digital ordering powered by", callInfo: "Napišite šta vam je potrebno. Osoblje će dobiti poruku s brojem vaše sobe.", placeholder: "Npr. Molim dodatne peškire.", send: "Pošalji zahtjev", cancel: "Odustani", sending: "Slanje…", required: "Napišite poruku od najmanje 3 znaka.", cooldown: "Osoblje možete pozvati jednom svake tri minute.", called: "Osoblje je obaviješteno.", callError: "Zahtjev trenutno nije moguće poslati.", weatherLabels: { sunny: "Sunčano", mostlySunny: "Pretežno sunčano", partlyCloudy: "Djelimično oblačno", cloudy: "Oblačno", foggy: "Magla", drizzle: "Rominjanje", rain: "Kiša", snow: "Snijeg", storm: "Oluja", default: "Promjenjivo" },
  }),
  en: withWeather({
    language: "Language", welcome: "Welcome", room: "Room", quickInfo: "Essential information", wifi: "Wi‑Fi", copyPassword: "Copy password", passwordCopied: "Password copied", copyError: "Password could not be copied", weather: "Weather", weatherLoading: "Loading weather", weatherUnavailable: "Weather is unavailable", breakfast: "Breakfast", wellness: "Wellness", restaurantRoomService: "Restaurant & room service", menuOrder: "Menu & ordering", menuText: "Food, drinks and room service", viewMenu: "View menu", hotelServices: "Hotel services", wellnessText: "Services and amenities", hotelInformation: "Hotel information", hotelInformationText: "Rules and information", call: "Call staff", callText: "Request assistance in your room", location: "Location", locationText: "Map and directions", poweredBy: "Digital ordering powered by", callInfo: "Tell us what you need. Staff will receive the message with your room number.", placeholder: "For example, please bring extra towels.", send: "Send request", cancel: "Cancel", sending: "Sending…", required: "Enter a message with at least 3 characters.", cooldown: "You can call staff once every three minutes.", called: "Staff has been notified.", callError: "The request could not be sent.", weatherLabels: { sunny: "Sunny", mostlySunny: "Mostly sunny", partlyCloudy: "Partly cloudy", cloudy: "Cloudy", foggy: "Foggy", drizzle: "Drizzle", rain: "Rain", snow: "Snow", storm: "Storm", default: "Changeable" },
  }),
  de: withWeather({
    language: "Sprache", welcome: "Willkommen", room: "Zimmer", quickInfo: "Wichtige Informationen", wifi: "WLAN", copyPassword: "Passwort kopieren", passwordCopied: "Passwort kopiert", copyError: "Passwort konnte nicht kopiert werden", weather: "Wetter", weatherLoading: "Wetter wird geladen", weatherUnavailable: "Wetter ist nicht verfügbar", breakfast: "Frühstück", wellness: "Wellness", restaurantRoomService: "Restaurant & Zimmerservice", menuOrder: "Menü & Bestellung", menuText: "Speisen, Getränke und Zimmerservice", viewMenu: "Menü ansehen", hotelServices: "Hoteldienstleistungen", wellnessText: "Services und Ausstattung", hotelInformation: "Hotelinformationen", hotelInformationText: "Regeln und Informationen", call: "Personal rufen", callText: "Hilfe im Zimmer anfordern", location: "Standort", locationText: "Karte und Anfahrt", poweredBy: "Digital ordering powered by", callInfo: "Schreiben Sie, was Sie benötigen. Das Personal erhält Ihre Zimmernummer.", placeholder: "Zum Beispiel: zusätzliche Handtücher.", send: "Anfrage senden", cancel: "Abbrechen", sending: "Wird gesendet…", required: "Geben Sie mindestens 3 Zeichen ein.", cooldown: "Sie können das Personal alle drei Minuten rufen.", called: "Das Personal wurde benachrichtigt.", callError: "Die Anfrage konnte nicht gesendet werden.", weatherLabels: { sunny: "Sonnig", mostlySunny: "Meist sonnig", partlyCloudy: "Teilweise bewölkt", cloudy: "Bewölkt", foggy: "Nebelig", drizzle: "Nieselregen", rain: "Regen", snow: "Schnee", storm: "Gewitter", default: "Wechselhaft" },
  }),
  tr: withWeather({
    language: "Dil", welcome: "Hoş geldiniz", room: "Oda", quickInfo: "Temel bilgiler", wifi: "Wi‑Fi", copyPassword: "Şifreyi kopyala", passwordCopied: "Şifre kopyalandı", copyError: "Şifre kopyalanamadı", weather: "Hava durumu", weatherLoading: "Hava durumu yükleniyor", weatherUnavailable: "Hava durumu kullanılamıyor", breakfast: "Kahvaltı", wellness: "Wellness", restaurantRoomService: "Restoran ve oda servisi", menuOrder: "Menü ve sipariş", menuText: "Yiyecek, içecek ve oda servisi", viewMenu: "Menüyü görüntüle", hotelServices: "Otel hizmetleri", wellnessText: "Hizmetler ve olanaklar", hotelInformation: "Otel bilgileri", hotelInformationText: "Kurallar ve bilgiler", call: "Personeli çağır", callText: "Odanız için yardım isteyin", location: "Konum", locationText: "Harita ve yol tarifi", poweredBy: "Digital ordering powered by", callInfo: "İhtiyacınızı yazın. Personel oda numaranızla birlikte mesajı alacaktır.", placeholder: "Örn. Ekstra havlu lütfen.", send: "Talep gönder", cancel: "Vazgeç", sending: "Gönderiliyor…", required: "En az 3 karakter yazın.", cooldown: "Personeli üç dakikada bir çağırabilirsiniz.", called: "Personele haber verildi.", callError: "Talep gönderilemedi.", weatherLabels: { sunny: "Güneşli", mostlySunny: "Çoğunlukla güneşli", partlyCloudy: "Parçalı bulutlu", cloudy: "Bulutlu", foggy: "Sisli", drizzle: "Çiseleme", rain: "Yağmur", snow: "Kar", storm: "Fırtına", default: "Değişken" },
  }),
  ar: withWeather({
    language: "اللغة", welcome: "مرحبًا", room: "غرفة", quickInfo: "المعلومات الأساسية", wifi: "واي فاي", copyPassword: "نسخ كلمة المرور", passwordCopied: "تم نسخ كلمة المرور", copyError: "تعذر نسخ كلمة المرور", weather: "الطقس", weatherLoading: "جارٍ تحميل الطقس", weatherUnavailable: "الطقس غير متاح", breakfast: "الإفطار", wellness: "العافية", restaurantRoomService: "المطعم وخدمة الغرف", menuOrder: "القائمة والطلب", menuText: "الطعام والمشروبات وخدمة الغرف", viewMenu: "عرض القائمة", hotelServices: "خدمات الفندق", wellnessText: "الخدمات والمرافق", hotelInformation: "معلومات الفندق", hotelInformationText: "القواعد والمعلومات", call: "استدعاء الموظفين", callText: "اطلب المساعدة في غرفتك", location: "الموقع", locationText: "الخريطة والاتجاهات", poweredBy: "Digital ordering powered by", callInfo: "اكتب ما تحتاجه. سيتلقى الموظفون الرسالة مع رقم غرفتك.", placeholder: "مثال: مناشف إضافية من فضلك.", send: "إرسال الطلب", cancel: "إلغاء", sending: "جارٍ الإرسال…", required: "اكتب رسالة من 3 أحرف على الأقل.", cooldown: "يمكنك استدعاء الموظفين مرة كل ثلاث دقائق.", called: "تم إبلاغ الموظفين.", callError: "تعذر إرسال الطلب.", weatherLabels: { sunny: "مشمس", mostlySunny: "مشمس غالبًا", partlyCloudy: "غائم جزئيًا", cloudy: "غائم", foggy: "ضبابي", drizzle: "رذاذ", rain: "مطر", snow: "ثلج", storm: "عاصفة", default: "متغير" },
  }),
};
